import Navbar from "../components/navbar/Navbar";


export const metadata = {
  title: "BloGue.id - Dashboard",
  description: "Generated by create next app",
};

export default function LandingPage({ children }) {
  return (
    <main className="">
        <Navbar />
        {children}
    </main>
);
}